remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-spaceship
title: "Cross-Disciplinary Software Team Spaces: A Pattern Language"
description: Patterns for Cross-Disciplinary Software Product Teams
show_downloads: false
google_analytics: G-CRHTQJZJBY