remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-spaceship
title: "Cross-Disciplinary Software Team Spaces"
description: A Pattern Language
show_downloads: false
google_analytics: G-CRHTQJZJBY
repository: kjetiljd/PatternsForCrossDisciplinarySoftwareTeamSpaces
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty
exclude:
  - CLAUDE.md
include:
  - "*.mp4"
